CREATE TABLE `match` (
  `id` int(11) NOT NULL COMMENT '球队ID',
  `color` char(7) NOT NULL COMMENT '颜色值',
  `league_id` int(11) UNSIGNED DEFAULT 0 COMMENT '联赛ID',
  `begin_time` varchar(20) DEFAULT 0 COMMENT '比赛时间',
  `sub_league` varchar(64) DEFAULT 0 COMMENT '联赛子类型',
  `status` tinyint(1) UNSIGNED DEFAULT NULL COMMENT '比赛状态',
  `home_id` int(11) UNSIGNED DEFAULT NULL COMMENT '主队ID',
  `away_id` int(11) UNSIGNED DEFAULT NULL COMMENT '客队ID',
  `home_score` tinyint(2) UNSIGNED DEFAULT 1 COMMENT '主队比分',
  `away_score` tinyint(2) UNSIGNED DEFAULT 38 COMMENT '客队比分',
  `home_half_score` tinyint(2) UNSIGNED DEFAULT 1 COMMENT '主队半场比分',
  `away_half_score` tinyint(2) UNSIGNED DEFAULT NULL COMMENT '客队半场比分',
  `home_red` tinyint(1) UNSIGNED DEFAULT NULL COMMENT '主队红牌',
  `away_red` tinyint(1) UNSIGNED DEFAULT NULL COMMENT '客队红牌',
  `home_rank` int(11) UNSIGNED DEFAULT NULL COMMENT '主队当前排名',
  `away_rank` int(11) UNSIGNED DEFAULT NULL COMMENT '客队当前排名',
  `match_desc` varchar (255)  DEFAULT NULL COMMENT '比赛描述',
  `round` int(16) UNSIGNED DEFAULT 1 COMMENT '轮次',
  `area` varchar(16) DEFAULT NULL COMMENT '比赛地点',
  `weather_icon` tinyint(1) UNSIGNED DEFAULT 1 COMMENT '天气图标',
  `weather` varchar(16) DEFAULT NULL COMMENT '天气',
  `temperature` varchar(16) DEFAULT NULL COMMENT '温度',
  `season` varchar(16) DEFAULT NULL COMMENT '赛季',
  `group` varchar(16) DEFAULT NULL COMMENT '小组分组',
  `is_neutral` varchar(16) DEFAULT NULL COMMENT '是否中立场地',
  `sub_league_id` int(11) UNSIGNED DEFAULT NULL COMMENT '子联赛ID',
  PRIMARY KEY (`id`),
  KEY `league_id` (`league_id`) USING BTREE,
  KEY `home_id` (`home_id`) USING BTREE,
  KEY `away_id` (`away_id`) USING BTREE,
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

